### ISSUE TITLE
oauth 로그인 로직 수정 

### ISSUE THREAD

**Issue by AhGnuesHo** [a-co-ha/server#23]
서버에서 바로 깃허브 로그인을 요청하면 
 깃허브내에서 유저 정보를 보내주는 url이 다르기 때문에 
서버에서 cors로 열어줘도 cors 에러가 발생한다. 
 
클라이언트에서 먼저 깃허브로 요청해서 권한코드를 부여받고 
코드를 서버가 받아서 처리해야함 
[참고자료
](https://gisungcu.tistory.com/205)

<img width="566" alt="image" src="https://user-images.githubusercontent.com/69295153/224467229-8fbf9948-4cf0-478f-a3a0-6a82568f62f2.png">

**Comment by tangjinlog** [comment]
<br/>- **문제 발생 flow**
1. 프론트에서 백엔드에 oauth 로그인 API 요청
2. 백엔드에서 passport 라이브러리로 github authenticate를 진행. 이 과정에서 프론트 사용자에게 github 인증을 요구하는데 여기서 CORS 에러 발생.
```js
https://github.com/login/oauth/authorize
```

위 api로 사용자에게 인증을 받기위해 프론트에 redirection 시킨다.
서버에서 cors 설정을 다 열어주고 프론트에서 서버 주소로 proxy도 적용시켰지만 아래와 같은 302에러 발생 

<img width="654" alt="image" src="https://user-images.githubusercontent.com/96574345/224750495-99da8d0e-3155-46aa-ae48-3b7878f8a171.png">
서버의 다른 API요청은 에러가 안나는것으로 봐서 github API가 cors를 허용하지않기 때문에 redirection 과정에서 cors 에러가 나는것으로 보인다.

<br /> - **수정 flow**
1. 프론트에서 github authorize API를 요청해서 인가 코드를 받는다.
2. 인가 코드를 백엔드 oauth 로그인 API에 담아 보낸다.
3. 백엔드에서 사용자 정보를 조회하고 토큰을 생성해 프론트에 응답한다.

수정한 1번 방법에서 기존 axios.get요청 대신 <Link> 태그의 href 속성을 이용했다.
이유는 github API에서 프론트에 redirection 시킬 때 cookie에 인증 정보들을 담아서 넘겨주는데 이 중,
SameSite=Lax라는 옵션이 top-level-navigation이 아니면 안되기 때문이다.
axios의 요청은 허용하지않고 a태그의 href 속성이나 window.location.href 속성을 허용한다.

[SameSite]
https://seob.dev/posts/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-%EC%BF%A0%ED%82%A4%EC%99%80-SameSite-%EC%86%8D%EC%84%B1/

검색해보니 기존 브라우저들의 SameSite 보안 등급이 올라가서 cookie 인증방식의 OAuth 로그인이 문제를 겪는 걸로 보인다. 

최종적으로 nextjs의 Link 태그의 href속성을 이용한 top-level-navigation으로 인가 코드를 프론트에서 먼저 받고
axios.get요청으로 인가코드를 담아 보내서 accessToken을 발급받는 flow로 해결했다.

```js
 <Link  href={`https://github.com/login/oauth/authorize?client_id=${process.env.NEXT_PUBLIC_GITHUB_OAUTH_CLIENT_ID}&redirect_uri=http://localhost:3001/oauth/callback`}>
Github 로그인
</Link>
```

**Comment by AhGnuesHo** [comment]
`passport.js` 전략은 내부적으로 깃허브에서 
1.Auth Code를 발급받고 -> 
2. Auth Code를 통해 access_token발급 -> 
3. access_token을 통해 user정보를 얻어오는 과정을 한꺼번에 수행해준다. 

 1번과정이 클라이언트에서 이루어지기 때문에 패스포트상에서 2번 과정인 access_token을 바로 요청해서 받아오고 싶었지만 그런 방법은 없는 것 같았다. 

그래서 패스포트를 포기하고 직접 axios요청을 통해 access_token 및 user 정보를 받는 것으로 수정했다. 

```js
 const requestToken = req.query.code;
  axios({
    method: "post",
    url: `https://github.com/login/oauth/access_token?client_id=${oauthClient}&client_secret=${oauthSecret}&code=${requestToken}`,

    headers: {
      accept: "application/json",
    },
  }).then(async (response: any) => {
    const access_token = response.data.access_token;
    axios({
      method: "get",
      url: `https://api.github.com/user`,
      headers: {
        Authorization: "Bearer " + access_token,
      },
    }).then(async (response) => {
      const {
        id,
        name,
        login: githubID,
        html_url: githubURL,
        avatar_url: img,
      } = response.data;

      const user: UserAttributes = { id, name, githubID, githubURL, img };

      const isGuest = await userService.get(user);
...
```
todo 
1. 패스포트를 사용하지 않는 대신 패스포트가 대신 하고 있었던 세션 검증과 같은 기능들을 추가해야한다. 
2. url 주소같은 것은 문자열을 그대로 두지 말고 상수화해서 사용
